#!/bin/bash

# skip this hook if using --no-verify flag
if [ "$NO_VERIFY" ]; then
    echo 'pre-commit hook skipped' 1>&2
    exit 0
fi

# get message commit
commit_msg=$(< "$1")

# set allowed flags
allowed_flags=("feat:" "fix:" "perf:" "docs:" "style:" "refactor:" "test:" "build:" "conf:")

# gets first word from the git message
first_word=$(echo "$commit_msg" | awk 'NR==1 {print $1}')

# Checks if commit starts with one of those flags
flag_found=0
for flag in "${allowed_flags[@]}"; do
    if [[ "$flag" == "$first_word" ]]; then
        flag_found=1
        break
    fi
done

if [[ $flag_found -eq 0 ]]; then
    echo "ERROR: Your commit message must starts with one of the following flags: ${allowed_flags[@]}" >&2
    exit 1
fi
