#!/bin/bash

# Captura a mensagem do commit
commit_msg=$(< "$1")

# Define as flags permitidas
allowed_flags=("feat:" "fix:" "perf:" "docs:" "style:" "refactor:" "test:" "build:" "Merge")

# Extrai a primeira palavra da mensagem de commit
first_word=$(echo "$commit_msg" | awk 'NR==1 {print $1}')

# Verifica se a primeira palavra está entre as flags permitidas
flag_found=0
for flag in "${allowed_flags[@]}"; do
    if [[ "$flag" == "$first_word" ]]; then
        flag_found=1
        break
    fi
done

if [[ $flag_found -eq 0 ]]; then
    echo "Erro: A mensagem de commit deve começar com uma das seguintes ${red}flags: ${allowed_flags[@]}${reset}" >&2
    exit 1
fi